import Head from 'next/head'
import PizzaList from '../components/PizzaList'
import Slider from '../components/Slider'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Slider />
        <PizzaList />
      </div>
  )
}
